### ISSUE TITLE
C treatment in CvD_SSP_tools.py

### ISSUE THREAD

**Issue by afeldmei** [samvaughan/PyStaff#9]
Hi Sam, 

I think I found a bug, but plese confirm:
When the code makes the general correction templates 

(y=(var_elem_spectra[e].flam[c, d, t_mask]/var_elem_spectra['Solar'].flam[c, d, t_mask]-1)*((10**(gen_step)-1.0)/(10**(0.3)-1.0)))

it uses 0.3 as value of the  enhancement of the reference spectra. However, Carbon is the only element for which the Conroy+2018 spectra have a reference enhancement of 0.15 dex and not 0.3 dex. So it should be 

(y=(var_elem_spectra[e].flam[c, d, t_mask]/var_elem_spectra['Solar'].flam[c, d, t_mask]-1)*((10**(gen_step)-1.0)/(10**(0.15)-1.0)))

for Carbon. Or am I missing something?

Thanks!
Anja

**Comment by samvaughan** [comment]
Hi Anja, 

Thanks very much for pointing this out! You're absolutely correct, the Carbon templates are enhancements of +0.15 and -0.15 dex rather than +/-0.3 dex. In previous work I just halved the derived abundances of Carbon I'd found to reflect this fact (i.e. True carbon abundance = Pystaff abundance/2) but thinking about it again I don't think that's the correct thing to do. I'll add in an 'if' statement to the CvD_SSP_tools.py code and then update the prior in fit_example.py to reflect this.

Thanks again!
Sam

**Comment by samvaughan** [comment]
Okay, I've updated the code- it's now treating Carbon completely separately from the other elements (more similar to the way Na is treated). A couple of other things:

- I've also moved the instrumental resolution convolution to the start (when everything is being set up) rather than doing so when the likelihood function is evaluated
- I've also made things a bit quicker when you set lots of elements not to vary- we now check which elements are fixed and only look up the correction for elements which are varying. This saves a surprising amount of time!

Let me know if you have any issues with the new version :-) 

Sam

**Comment by afeldmei** [comment]
Hi Sam, 

Thanks for the update! 
However, I think there is a bug in the new version:

    print('Making the Carbon Correction template')
    for b, step in enumerate(C_elem_steps):
        for c, _ in enumerate(ages):
            for d, _ in enumerate(Zs):

                if step>0.0:
                    e='{}+'.format(elem)
                    gen_step=step
                elif step<0.0:
                    e='{}-'.format(elem)
                    gen_step=np.abs(step)

does not seem to find the correct carbon enhanced templates. I modified it to 

    print('Making the Carbon Correction template')
    for b, step in enumerate(C_elem_steps):
        for c, _ in enumerate(ages):
            for d, _ in enumerate(Zs):
                if step>0.0:
                    e='C+'
                    gen_step=step
                elif step<0.0:
                    e='C-'
                    gen_step=np.abs(step)


Another thing that did not work was the convolution with the instrumental_resolution. 

In CvDTools.prepare_CvD_interpolator_twopartIMF (and CvDTools.prepare_CvD_correction_interpolators), when sspNew is convolved, the arrays have a different size. I tried a couple of things and I wonder what you think:
The convolution happens in rebinned log space, doesn't this mean one should pass log_instrumental_resolution instead of instrumental_resolution? 
But in any case, instrumental_resolution (or log_instrumental_resolution)  has the same length as galaxy (or loggalaxy), which is less than sspNew, so I get error messages. What I did is pass log_instrumental_resolution and the corresponding wavelength vector, and then simply extrapolate log_instrumental_resolution such that it has the same array size as sspNew.

Cheers, 
Anja

**Comment by samvaughan** [comment]
Hi Anja, 

> However, I think there is a bug in the new version:

Yep, you're completely right- well spotted! I will fix that ASAP (probably tomorrow morning my time).

> Another thing that did not work was the convolution with the instrumental_resolution.

> In CvDTools.prepare_CvD_interpolator_twopartIMF (and CvDTools.prepare_CvD_correction_interpolators), when sspNew is convolved, the arrays have a different size. I tried a couple of things and I wonder what you think:

> But in any case, instrumental_resolution (or log_instrumental_resolution) has the same length as galaxy (or loggalaxy), which is less than sspNew, so I get error messages. What I did is pass log_instrumental_resolution and the corresponding wavelength vector, and then simply extrapolate log_instrumental_resolution such that it has the same array size as sspNew.

Yeah, the test case I ran mine on used an instrumental resolution function, which returns the instrumental resolution at any wavelength (in my case, a polynomial fit to the measured instrumental resolution). This got around the issue that the arrays are different sizes. As you say, extrapolating the instrumental resolution to be the same size as the templates is another way to do it- the extrapolation won't matter because the templates are chopped to close to the galaxy anyway (where you should know the instrumental resolution!). I'll add in another test case and update the documentation to make this clearer.

> The convolution happens in rebinned log space, doesn't this mean one should pass log_instrumental_resolution instead of instrumental_resolution?

I don't think we should be passing log(instrumental resolution), if that's what you meant. I could move the convolution with the instrumental resolution to before the log-rebinning, of course. I'll investigate this further tomorrow and get back to you!

Apologies for the changes I made last week not working for you. I do think that convolving the templates with the instrumental resolution once (i..e not each time during the likelihood evaluation) is the better way to do things, though.

Thanks again for your help with the code!
Sam

**Comment by samvaughan** [comment]
Hi Anja, 

I've made the changes to the code. It's currently in the "dev" branch of this repository. Would you mind having a look at it and seeing if it works with your data? 

The main change I've made is to the instrumental resolution. This must now be a function which returns the instrumental resolution (in km/s) at any wavelength. If you have the instrumental resolution as an array which is the same length of your data, the quickest way to do this is something like:

```python
lamdas, flux, errors, instrumental_resolution_values = np.genfromtxt(datafile, unpack=True)

def instrumental_resolution_function(wavelength_we_want_to_know_sigma_at):
    import scipy.interpolate as si 

    instrumental_resolution_interpolator = si.interp1d(lamdas, instrumental_resolution_values, bounds_error=False, fill_value=(instrumental_resolution_values[0], instrumental_resolution_values[-1]))

    return instrumental_resolution_interpolator(wavelength_we_want_to_know_sigma_at)
```

The templates are then convolved to match this resolution. Note that the templates are at a constant resolution of 100km/s already.

This function will extrapolate the instrumental resolution above and below the wavelength values of your data- but this is okay since we're going to ignore the regions of the templates which are far from the data anyway.

Thanks,
Sam

**Comment by afeldmei** [comment]
Thanks for the new version, it works for my data!

**Comment by samvaughan** [comment]
Great, thanks! I'll close this now.

Sam
